// Generated by CoffeeScript 1.8.0
(function() {
  var apiKey, checkAuth, clientId, handleAuthResult, handleClientLoad, loadClient, scopes;

  scopes = 'https://spreadsheets.google.com/feeds';

  clientId = '225160616080-rlae3dprbofq5i1etegg5vdvobf2rhqi.apps.googleusercontent.com';

  apiKey = '14OPwgdy9-2uTIS-x5CDMOYcn2Yo2kuML3Fn0tVMdWrA';

  handleClientLoad = function() {
    console.log("handleClientLoad");
    gapi.client.setApiKey(apiKey);
    return window.setTimeout(checkAuth, 1);
  };

  checkAuth = function() {
    console.log('checkAuth');
    gapi.auth.authorize({
      client_id: clientId,
      scope: scopes,
      immediate: true
    }, handleAuthResult);
    return console.log('finished checkAuth');
  };

  handleAuthResult = function(authResult) {
    return console.log("handleAuthResult", authResult);
  };

  loadClient = function() {
    var config;
    config = {
      'client_id': clientId,
      'scope': scopes
    };
    return gapi.auth.authorize(config, function() {
      var token, url;
      console.log('login complete');
      token = gapi.auth.getToken().access_token;
      console.log(token);
      url = 'https://spreadsheets.google.com/feeds/worksheets/' + apiKey + '/private/full?alt=json-in-script&access_token=' + token + '&callback=?';
      return $.getJSON(url, function(data) {
        console.log("got json");
        return console.log(data);
      });
    });
  };

  $("#authorize-button").click(loadClient);

}).call(this);
